apiVersion: v1
kind: ConfigMap
metadata:
  name: cvat-config
data:
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_PASSWORD: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@example.com"
