apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cvat-vector
  name: cvat-vector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-vector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cvat-vector
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_DB
              value: cvat
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: CLICKHOUSE_PASSWORD
              value: user
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: user
          image: timberio/vector:0.26.0-alpine
          name: cvat-vector
          volumeMounts:
            - mountPath: /etc/vector/vector.toml
              name: cvat-vector-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: cvat-vector-claim0
          persistentVolumeClaim:
            claimName: cvat-vector-claim0
            readOnly: true
