apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: cvat-events-db
  name: cvat-events-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
