apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cvat-clickhouse
  name: cvat-clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cvat-clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_DB
              value: cvat
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: CLICKHOUSE_PASSWORD
              value: user
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: user
          image: clickhouse/clickhouse-server:23.11-alpine
          name: cvat-clickhouse
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sh
              name: cvat-clickhouse-claim0
              readOnly: true
            - mountPath: /var/lib/clickhouse
              name: cvat-events-db
      restartPolicy: Always
      volumes:
        - name: cvat-clickhouse-claim0
          persistentVolumeClaim:
            claimName: cvat-clickhouse-claim0
            readOnly: true
        - name: cvat-events-db
          persistentVolumeClaim:
            claimName: cvat-events-db
