apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: traefik-claim1
  name: traefik-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
