# cvat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cvat
spec:
  selector:
    app: cvat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer  # Или NodePort, если LoadBalancer недоступен
