# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvat-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/cvat"  # Задайте путь на хосте
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

