apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-web
  template:
    metadata:
      labels:
        app: cvat-web
    spec:
      containers:
      - name: cvat-ui
        image: openvino/cvat_ui:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_HOST
          # Адрес сервера CVAT API
          value: http://cvat_server:8080
        - name: REACT_APP_API_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
